= Sample application for Flash Boot Loader for DEVKIT-MPC5748G
:Author:            Peter Vranken 
:Email:             mailto:Peter_Vranken@Yahoo.de
:toc:               left
:xrefstyle:         short
:numbered:
:icons:             font
:caution-caption:   :fire:
:important-caption: :exclamation:
:note-caption:      :paperclip:
:tip-caption:       :bulb:
:warning-caption:   :warning:

== About this DEVKIT-MPC5748G sample

This DEVKIT-MPC5748G sample implements a most simple demo application for
showing:

. How to use the flash boot loader (FBL) for the DEVKIT-MPC5748G.
. How to prepare an application to become compatible with the
requirements of the FBL.

== Behavior of the sample application

The application has a user interface based on serial I/O. You need to open
a terminal application on your development host machine, which the
evaluation board is connected to via USB. The NXP software implements a
virtual COM device on the host machine; open this COM channel with 115200
Bd, 8 Bit, no parity bit, 1 stop bit. 

The sample permanently prints some progress information but it takes no
user input and can't be influenced in what it does.

== Origin and modifications

The sample is a copy from
https://github.com/PeterVranken/DEVKIT-MPC5748G/tree/master/samples/startup[GitHub,
"startup"^]. Please go there for details of the application. The only
modification made is the boot header. The boot header has been moved to
another address - an address, which is recognized and supported by the FBL
- and it has two additional words of information.

TODOC: Details, address before and now, where have the modifications been made.

== Tools

=== Environment

==== Command line based build

The makefiles and related scripts require a few settings of the
environment in the host machine. In particular, the location of the GNU
compiler installation needs to be known and the PATH variable needs to
contain the paths to the required tools. 

For Windows users there is a shortcut to PowerShell in the root of this
GitHub project, which opens the shell with the prepared environment.
Furthermore, it creates an alias to the appropriate GNU make executable.
You can simply type `make` from any location to run MinGW32 GNU make.

The PowerShell process reads the script `setEnv.ps1`, located in the
project root, too, to configure the environment. This script requires
customization prior to its first use. Windows users open it in a text
editor and follow the given instructions that are marked by TODO tags.
Mainly, it's about specifying the installation directory of GCC.

Non-Windows users will read this script to see, which (few) environmental
settings are needed to successfully run the build and prepare an according
script for their native shell.

[[secOpenEclipse]]
==== Eclipse for building, flashing and debugging

Flashing and debugging is always done using the NXP S32 Design Studio for
Power Architecture, an Eclipse IDE, which is available for free download
and nearly unrestricted use in commercial and non commercial projects.

If you are going to run the application build from the Eclipse IDE then
the same environmental settings as described above for a shell based build
need to be done for Eclipse, too. The easiest way to do so is starting
Eclipse from a shell, that has executed the script `setEnv.ps1` prior to
opening Eclipse.

For Windows users the script `S32DS-IDE.ps1` has been prepared. This script
requires customization prior to its first use. Windows users open it in a
text editor and follow the given instructions that are marked by TODO
tags. Mainly, it's about specifying the installation directory of
the S32 Design Studio.

Non-Windows users will read this script to see, which (few) environmental
and path settings are needed to successfully run the build under control
of Eclipse and prepare an according script for their native shell.

Once everything is prepared, the S32 Design Studio will never be started
other than by clicking the script `S32DS-IDE.ps1` or its equivalent on
non-Windows hosts.

TODOC: Where to get the tools, how to install them
//See https://github.com/PeterVranken/TRK-USB-MPC5643L[project overview^] and
//https://github.com/PeterVranken/TRK-USB-MPC5643L/wiki/Tools-and-Installation[GitHub
//Wiki^] for more details about downloading and installing the required
//tools.

=== Compiler and makefile

Compilation and linkage are makefile controlled. The compiler is GCC
(MinGW-powerpc-eabivle-4.9.4). It is part of the S32 Design Studio
installation and can be used independently from the Studio. The makefile
is made generic and can be reused for production projects that want to
make use of safe-RTOS. It supports a number of options (targets); get an
overview by typing:
 
    cd <projectRoot>/samples/CAN
    mingw32-make help

The main makefile `GNUmakefile` has been configured for the build of
sample "CAN". Type:

    mingw32-make -sO build
    mingw32-make -sO build CONFIG=PRODUCTION

to produce the flashable files
`bin\ppc\default\DEBUG\DEVKIT-MPC5748G-startup.s28`, and
`bin\ppc\default\PRODUCTION\DEVKIT-MPC5748G-startup.s28`.

File `GNUmakefile` has a variable `defineList`, which is a list of options
for the build. A major option is `LINK_IN_RAM`. If you place this option
into the list then the same build commands link the software for execution
in RAM. (See next section for details). With option `LINK_IN_RAM`, the same
commands:

    mingw32-make -sO build
    mingw32-make -sO build CONFIG=PRODUCTION

produce the flashable files
`bin\ppc\default\DEBUG-RAM\DEVKIT-MPC5748G-startup.s28`, and
`bin\ppc\default\PRODUCTION-RAM\DEVKIT-MPC5748G-startup.s28`.

To get more information, type:

    mingw32-make --help
    mingw32-make help

WARNING: The makefile requires the MinGW port of the make processor. The
Cygwin port will fail with obscure, misleading error messages. For your
convenience, we have uploaded an appropriate recent version of the MinGW
make processor into this GitHub project. The PowerShell startup script
aliases this (Windows) executable to the command `make`. Moreover,
explicitly typing `mingw32-make` will generally avoid any problem.

The makefile is designed to run on different host systems but has been
tested with Windows 7 and Windows 10 only.

=== Flashing

TODOC: How to use flash tool and FBL
